---
title: "BLUE or BLUP: Which should be used for GWAS and GS?"
author: "Che-Wei Chang"
date: "2020-09-22"
output: html_document
bibliography: bib/ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

From the breeder's aspect, BLUP (best linear unbiased predictor) is commonly used for selection because it maximizes the probability of correct ranking [@searle2001generalized, chapter 9, p.254].      

On the other hand, using BLUEs (best linear unbiased estimators) of genotypes as response variables for association mapping or genomic prediction has been a conventional approach, but the reason for using BLUEs instead of BLUPs is unclear to me and not explained in the most of papers I found.  
  

  
In Prof. Jochen Reif's paper [@he2016genomic], the authors' argument is:  

> ... We used BLUEs as response variable for genomic selection and not de-regressed BLUPs as often used in animal breeding (Garrick et al. 2009; Ostersen et al. 2011; Weber et al. 2012). In wheat breeding, the main target of selection is the genotypic but not the breeding value. Therefore, BLUEs seems to be more appropriate as they reflect an estimate of the whole genotypic value and not solely the breeding value. ...

Another answer from the perspective of statistics is that BLUPs will cause shrinkage of genetic effects toward the mean according to the answer of [Prof. Salvador A. Gezan on researchgate](https://www.researchgate.net/post/Does_any_one_have_an_idea_of_which_one_BLUE_or_BLUP_to_use_for_a_GWAS_analysis_of_a_trait_in_wheat_eg_resistance_to_rust)  

> ... If you use BLUP then you are doing shrinkage of your genetic effects. This will mean that your genetic effects are moved towards the mean according to theri information, yes, they will be your best predictions of those random effects, but they will be adjusted by their sample size and the vairance associated with theri data. This is what a random effects does...  

**For the reason of why BLUPs shrink toward the mean, [Prof. Bruce Walsh gave the mathematical proof in his lecture note (see page 23 of the note) ](http://nitro.biosci.arizona.edu/workshops/TWIPB2013/Mod3/Mod3-5.pdf).** The degree of shrinkage is equal to heritability ($BLUP = h^2(y-\mu)$ ). As shown in the formula, BLUPs shrink toward 0 since the random effect is assumed following $N(0, \sigma^2)$.  
  
### Conclusion
BLUEs should be used for association mapping and genomic prediction due to the shrinkage of BLUPs may eliminate genetic effects.  
   
## Reference